export const secondarySidebarNavigationItems = [
  { label: "Source Health", path: "/source-health" },
  { label: "Executive Dashboard", path: "/executive-dashboard" },
  { label: "Profitability Analytics", path: "/profitability-analytics" },
  { label: "Operational Forecasting", path: "/operational-forecasting" },
  { label: "RFQ Intelligence", path: "/qualification-insights" },
  { label: "Pricing Evidence", path: "/pricing-evidence" },
  { label: "Review Workflow", path: "/review" },
  { label: "Queue Monitor", path: "/review" },
  { label: "Operational Health", path: "/runtime-operations" },
  { label: "Operator Operations", path: "/operator-operations" },
  { label: "Operator Productivity", path: "/operator-productivity" },
  { label: "Queue Optimization", path: "/queue-optimization" },
  { label: "Review Efficiency", path: "/review-efficiency" },
  { label: "Operator Shortcuts", path: "/operator-productivity" },
  { label: "Governance / Compliance Review", path: "/governance-compliance" },
  { label: "Audit Defensibility", path: "/audit-defensibility" },
  { label: "Compliance Reporting", path: "/compliance-reporting" },
  { label: "Runtime Operations", path: "/runtime-operations" },
  { label: "Operational Analytics", path: "/operational-analytics" },
  { label: "Incident Management", path: "/incident-management" },
  { label: "Observability", path: "/observability" },
  { label: "SLA Monitoring", path: "/sla-monitoring" },
  { label: "Runtime Anomalies", path: "/runtime-anomalies" },
  { label: "Stabilization Operations", path: "/stabilization-operations" },
  { label: "Operator Feedback", path: "/operator-feedback" },
  { label: "Runtime Reliability", path: "/runtime-reliability" },
  { label: "Activity Timeline", path: "/activity-timeline" },
];
