DEPARTMENT_SOURCES = [
    {
        "name": "Agriculture",
        "homepage_url": "https://www.nda.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Basic Education",
        "homepage_url": "https://www.education.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Civilian Secretariat for Police",
        "homepage_url": "https://www.policesecretariat.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Communications and Digital Technologies",
        "homepage_url": "https://www.dcdt.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Cooperative Governance and Traditional Affairs",
        "homepage_url": "https://www.cogta.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Correctional Services",
        "homepage_url": "https://www.dcs.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Defence",
        "homepage_url": "https://www.dod.mil.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Electricity and Energy",
        "homepage_url": "https://www.dmre.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Employment and Labour",
        "homepage_url": "https://www.labour.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Forestry, Fisheries and the Environment",
        "homepage_url": "https://www.dffe.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Government Communication and Information System",
        "homepage_url": "https://www.gcis.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Health",
        "homepage_url": "https://www.health.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Higher Education (Higher Education and Training)",
        "homepage_url": "https://www.dhet.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Home Affairs",
        "homepage_url": "https://www.dha.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Human Settlements",
        "homepage_url": "https://www.dhs.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Independent Police Investigative Directorate",
        "homepage_url": "https://www.ipid.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "International Relations and Cooperation",
        "homepage_url": "https://www.dirco.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Justice and Constitutional Development",
        "homepage_url": "https://www.justice.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Land Reform and Rural Development",
        "homepage_url": "https://www.dlrrd.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Military Veterans",
        "homepage_url": "https://www.dmv.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Mineral and Petroleum Resources",
        "homepage_url": "https://www.dmre.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "National School of Government",
        "homepage_url": "https://www.thensg.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "National Treasury",
        "homepage_url": "https://www.treasury.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Office of the Chief Justice",
        "homepage_url": "https://www.judiciary.org.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Planning Monitoring and Evaluation",
        "homepage_url": "https://www.dpme.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Public Service and Administration",
        "homepage_url": "https://www.dpsa.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Public Service Commission",
        "homepage_url": "https://www.psc.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Public Works and Infrastructure",
        "homepage_url": "https://www.publicworks.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Science, Technology and Innovation",
        "homepage_url": "https://www.dsti.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Small Business Development",
        "homepage_url": "https://www.dsbd.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Social Development",
        "homepage_url": "https://www.dsd.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "SA Police Service",
        "homepage_url": "https://www.saps.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "SA Revenue Service",
        "homepage_url": "https://www.sars.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "State Security Agency",
        "homepage_url": "https://www.ssa.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Sport, Arts and Culture",
        "homepage_url": "https://www.dsac.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Statistics South Africa",
        "homepage_url": "https://www.statssa.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Tourism",
        "homepage_url": "https://www.tourism.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Trade, Industry and Competition",
        "homepage_url": "https://www.thedtic.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Transport",
        "homepage_url": "https://www.transport.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Water and Sanitation",
        "homepage_url": "https://www.dws.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "Women, Youth and Persons with Disabilities",
        "homepage_url": "https://www.dwypd.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
    {
        "name": "The Presidency",
        "homepage_url": "https://www.thepresidency.gov.za",
        "rfq_url": None,
        "notes": "Seeded from official national departments directory.",
    },
]
