from __future__ import annotations

from html import escape
from pathlib import Path

from app.models import QuoteDraft, Opportunity


BASE_DIR = Path(__file__).resolve().parent.parent
QUOTE_OUTPUT_DIR = BASE_DIR / "generated_quotes"


def ensure_quote_output_dir() -> None:
    QUOTE_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def _safe(value):
    return "" if value is None else str(value)


def build_line_items_table(quote: QuoteDraft) -> str:
    rows = []
    for item in sorted(quote.line_items, key=lambda x: (x.line_no, x.id)):
        match_meta = ""
        if item.auto_generated:
            match_meta = f"<div style='font-size:11px;color:#6b7280;'>Auto-match score: {item.match_score or 0:.2f} | {escape(_safe(item.match_reason))}</div>"

        rows.append(
            f"""
            <tr>
                <td>{item.line_no}</td>
                <td>{escape(_safe(item.item_name))}</td>
                <td>{escape(_safe(item.description))}{match_meta}</td>
                <td>{escape(_safe(item.unit))}</td>
                <td class="right">{item.quantity:,.2f}</td>
                <td class="right">{item.unit_cost:,.2f}</td>
                <td class="right">{item.markup_pct:,.2f}%</td>
                <td class="right">{item.unit_sell_price:,.2f}</td>
                <td class="right">{item.line_total_ex_vat:,.2f}</td>
            </tr>
            """
        )

    if not rows:
        rows.append(
            """
            <tr>
                <td>1</td>
                <td>Quotation Summary</td>
                <td>Auto-generated draft with no item lines added yet.</td>
                <td>sum</td>
                <td class="right">1.00</td>
                <td class="right">0.00</td>
                <td class="right">0.00%</td>
                <td class="right">0.00</td>
                <td class="right">0.00</td>
            </tr>
            """
        )

    return "\n".join(rows)


def build_quote_html(quote: QuoteDraft, opportunity: Opportunity) -> str:
    title = escape(_safe(opportunity.title))
    buyer = escape(_safe(opportunity.buyer_name or "Client"))
    province = escape(_safe(opportunity.province or ""))
    category = escape(_safe(opportunity.category or ""))
    source = escape(_safe(opportunity.source or ""))
    source_url = escape(_safe(opportunity.source_url or ""))
    pricing_notes = escape(_safe(quote.pricing_notes or ""))
    scope_summary = escape(
        _safe(
            quote.scope_summary
            or opportunity.description
            or "Supply and delivery quotation generated by LMCP AutoQuote."
        )
    )

    line_items_html = build_line_items_table(quote)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>{escape(quote.quote_number)} - LMCP Quotation</title>
    <style>
        body {{
            font-family: Arial, Helvetica, sans-serif;
            margin: 30px;
            color: #111827;
            font-size: 13px;
        }}
        .header {{
            border-bottom: 3px solid #1f2937;
            padding-bottom: 12px;
            margin-bottom: 20px;
        }}
        .company {{
            font-size: 24px;
            font-weight: 700;
        }}
        .sub {{
            font-size: 12px;
            color: #4b5563;
            margin-top: 6px;
            line-height: 1.5;
        }}
        .section {{
            margin-top: 20px;
        }}
        .section-title {{
            font-size: 15px;
            font-weight: 700;
            border-bottom: 1px solid #d1d5db;
            padding-bottom: 6px;
            margin-bottom: 10px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
        }}
        th, td {{
            border: 1px solid #d1d5db;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }}
        th {{
            background: #f3f4f6;
        }}
        .right {{
            text-align: right;
        }}
        .footer {{
            margin-top: 30px;
            font-size: 12px;
            color: #4b5563;
        }}
    </style>
</head>
<body>
    <div class="header">
        <div class="company">Lechesa Manaba Consulting and Projects (Pty) Ltd</div>
        <div class="sub">
            Auto-generated itemized quotation draft<br/>
            Quote Number: {escape(quote.quote_number)}<br/>
            Client: {buyer}
        </div>
    </div>

    <div class="section">
        <div class="section-title">Opportunity Details</div>
        <table>
            <tr><th style="width: 220px;">Opportunity Title</th><td>{title}</td></tr>
            <tr><th>Buyer</th><td>{buyer}</td></tr>
            <tr><th>Province</th><td>{province}</td></tr>
            <tr><th>Category</th><td>{category}</td></tr>
            <tr><th>Source</th><td>{source}</td></tr>
            <tr><th>Source URL</th><td>{source_url}</td></tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Scope Summary</div>
        <p>{scope_summary}</p>
    </div>

    <div class="section">
        <div class="section-title">Itemized Pricing</div>
        <table>
            <tr>
                <th style="width: 50px;">#</th>
                <th style="width: 180px;">Item</th>
                <th>Description</th>
                <th style="width: 70px;">Unit</th>
                <th style="width: 90px;">Qty</th>
                <th style="width: 110px;">Unit Cost</th>
                <th style="width: 100px;">Markup %</th>
                <th style="width: 110px;">Unit Sell</th>
                <th style="width: 130px;">Line Total Excl. VAT</th>
            </tr>
            {line_items_html}
        </table>
    </div>

    <div class="section">
        <div class="section-title">Commercial Totals</div>
        <table>
            <tr><th style="width: 220px;">Base Cost</th><td class="right">{quote.base_cost:,.2f}</td></tr>
            <tr><th>Sell Price Excl. VAT</th><td class="right">{quote.sell_price_ex_vat:,.2f}</td></tr>
            <tr><th>VAT ({quote.vat_pct:.2f}%)</th><td class="right">{quote.vat_amount:,.2f}</td></tr>
            <tr><th>Total Incl. VAT</th><td class="right"><strong>{quote.total_price_inc_vat:,.2f}</strong></td></tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Notes</div>
        <p>{pricing_notes}</p>
    </div>

    <div class="footer">
        Internal LMCP draft quotation. Final review and approval required before submission.
    </div>
</body>
</html>
"""
    return html


def write_quote_document(quote: QuoteDraft, opportunity: Opportunity) -> tuple[str, str]:
    ensure_quote_output_dir()

    filename = f"{quote.quote_number}.html"
    path = QUOTE_OUTPUT_DIR / filename

    html = build_quote_html(quote=quote, opportunity=opportunity)

    with open(path, "w", encoding="utf-8") as f:
        f.write(html)

    return str(path), filename
