import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


TMP_DIR = "/tmp"


def _draw_title_page(c, title, subtitle_lines):
    width, height = A4

    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(width / 2, height - 100, title)

    c.setFont("Helvetica", 12)
    y = height - 150
    for line in subtitle_lines:
        c.drawCentredString(width / 2, y, line)
        y -= 22

    c.showPage()


def create_cover_page(quote) -> str:
    output_path = os.path.join(
        TMP_DIR,
        f"cover_page_{quote.quote_number}.pdf"
    )

    c = canvas.Canvas(output_path, pagesize=A4)

    today = datetime.today().strftime("%Y-%m-%d")

    title = "TENDER SUBMISSION PACK"
    subtitle_lines = [
        "Lechesa Manaba Consulting and Projects (Pty) Ltd",
        f"Quote Number: {quote.quote_number}",
        f"Prepared On: {today}",
        "Generated by LMCP Autonomous Tender Engine",
    ]

    # Optional fields if they exist on the quote/opportunity
    opportunity_title = getattr(getattr(quote, "opportunity", None), "title", None)
    buyer_name = getattr(getattr(quote, "opportunity", None), "buyer_name", None)

    if opportunity_title:
        subtitle_lines.insert(2, f"Opportunity: {opportunity_title}")

    if buyer_name:
        subtitle_lines.insert(3, f"Buyer / Institution: {buyer_name}")

    _draw_title_page(c, title, subtitle_lines)
    c.save()

    return output_path


def create_annexure_index(quote, included_sections: list[str]) -> str:
    output_path = os.path.join(
        TMP_DIR,
        f"annexure_index_{quote.quote_number}.pdf"
    )

    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 60, "ANNEXURE INDEX")

    c.setFont("Helvetica", 11)
    c.drawString(50, height - 85, f"Quote Number: {quote.quote_number}")

    y = height - 130
    row_no = 1

    for section in included_sections:
        c.setFont("Helvetica", 11)
        c.drawString(60, y, f"{row_no}. {section}")
        y -= 24
        row_no += 1

        if y < 80:
            c.showPage()
            y = height - 60

    c.save()
    return output_path
