apiVersion: v1
kind: Secret
metadata:
  name: backup-storage-secret-placeholder
type: Opaque
stringData:
  backup_endpoint: placeholder
  backup_access_key: placeholder
  backup_secret_key: placeholder
  encryption_at_rest: placeholder
  storage_provider: placeholder
