apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-lmcp-traffic
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: lmcp-autoquote
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: lmcp-autoquote
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: lmcp-autoquote
