apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-persistence-placeholder
data:
  persistence_enabled: "true"
  backup_safe: "true"
  persistence_mode: placeholder
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-backup-persistence-placeholder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
