from __future__ import annotations

import os


SUPPLY_WINS_TARGET_PER_MONTH = int(os.getenv("SUPPLY_WINS_TARGET_PER_MONTH", "4000"))
SUPPLY_MIN_PROFIT_PER_WIN = float(os.getenv("SUPPLY_MIN_PROFIT_PER_WIN", "30000"))
SUPPLY_MONTHLY_PROFIT_TARGET = SUPPLY_WINS_TARGET_PER_MONTH * SUPPLY_MIN_PROFIT_PER_WIN

SUPPLY_DEFAULT_WIN_RATE = float(os.getenv("SUPPLY_DEFAULT_WIN_RATE", "0.05"))
SUPPLY_DAYS_IN_MONTH = int(os.getenv("SUPPLY_DAYS_IN_MONTH", "30"))

SUPPLY_MIN_SCORE_TO_SUBMIT = float(os.getenv("SUPPLY_MIN_SCORE_TO_SUBMIT", "8.0"))
SUPPLY_MIN_SCORE_TO_REVIEW = float(os.getenv("SUPPLY_MIN_SCORE_TO_REVIEW", "6.0"))

SUPPLY_REJECT_IF_BELOW_MIN_PROFIT = os.getenv(
    "SUPPLY_REJECT_IF_BELOW_MIN_PROFIT",
    "true",
).strip().lower() in {"1", "true", "yes", "on"}

SUPPLY_DEFAULT_TAX_RATE = float(os.getenv("SUPPLY_DEFAULT_TAX_RATE", "0.15"))
